### ISSUE TITLE
flutter_localizations Error!!!!!

### ISSUE THREAD

**Issue by sagarshende23** [woosignal/flutter-woocommerce-app#1]
Because every version of flutter_localizations from sdk depends on intl 0.16.0 and flutter_money_formatter >=0.8.2 depends on intl ^0.15.8, flutter_localizations from sdk is incompatible with flutter_money_formatter >=0.8.2.

So, because flutter_woocomerce depends on both flutter_money_formatter ^0.8.2 and flutter_localizations any from SDK, version solving failed.
pub get failed (1; So, because flutter_woocomerce depends on both flutter_money_formatter ^0.8.2 and flutter_localizations
 any from SDK, version solving failed.)
exit code 1

![error](https://user-images.githubusercontent.com/43273993/73431375-4d403480-4366-11ea-9dc0-8e4b336fa8e5.jpg)

**Comment by sagarshende23** [comment]
Problem Solved After Adding this  line:
**dependency_overrides:
   intl:**

![33](https://user-images.githubusercontent.com/43273993/73592688-d4d2a280-4522-11ea-94b7-2a96f91c9d81.jpg)

**Comment by woosignal** [comment]
Thanks for spotting this, we've committed a patch
