### ISSUE TITLE
lib/main.dart:220:23: Error: Method not found: 'Hexcolor'.

### ISSUE THREAD

**Issue by TyagrajBhatt** [woosignal/flutter-woocommerce-app#12]
lib/main.dart:220:23: Error: Method not found: 'Hexcolor'.
        primaryColor: Hexcolor("#2f4ffe"),
                      ^^^^^^^^
lib/main.dart:224:24: Error: Method not found: 'Hexcolor'.
          buttonColor: Hexcolor("#529cda"),
                       ^^^^^^^^
lib/pages/account_billing_details.dart:184:40: Error: The method 'Hexcolor' isn't defined for the class '_AccountBillingDetailsPageState'.
 - '_AccountBillingDetailsPageState' is from 'package:label_storemax/pages/account_billing_details.dart' ('lib/pages/account_billing_details.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                color: Hexcolor("#e8e8e8"),
                                       ^^^^^^^^
lib/pages/account_detail.dart:348:42: Error: The method 'Hexcolor' isn't defined for the class '_AccountDetailPageState'.
 - '_AccountDetailPageState' is from 'package:label_storemax/pages/account_detail.dart' ('lib/pages/account_detail.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                  color: Hexcolor("#fcfcfc"),
                                         ^^^^^^^^
lib/pages/account_order_detail.dart:123:44: Error: The method 'Hexcolor' isn't defined for the class '_AccountOrderDetailPageState'.
 - '_AccountOrderDetailPageState' is from 'package:label_storemax/pages/account_order_detail.dart' ('lib/pages/account_order_detail.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                    color: Hexcolor("#fcfcfc"), width: 1),
                                           ^^^^^^^^
lib/pages/account_shipping_details.dart:203:40: Error: The method 'Hexcolor' isn't defined for the class '_AccountShippingDetailsPageState'.
 - '_AccountShippingDetailsPageState' is from 'package:label_storemax/pages/account_shipping_details.dart' ('lib/pages/account_shipping_details.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                color: Hexcolor("#e8e8e8"),
                                       ^^^^^^^^
lib/helpers/app_themes.dart:45:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#606060"),
               ^^^^^^^^
lib/helpers/app_themes.dart:49:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#a8a8a8"),
               ^^^^^^^^
lib/helpers/app_themes.dart:54:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#2a5080"),
               ^^^^^^^^
lib/helpers/app_themes.dart:94:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#606060"),
               ^^^^^^^^
lib/helpers/app_themes.dart:98:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#a8a8a8"),
               ^^^^^^^^
lib/helpers/app_themes.dart:103:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#2a5080"),
               ^^^^^^^^
lib/widgets/app_loader.dart:16:37: Error: Method not found: 'Hexcolor'.
  return SpinKitDoubleBounce(color: Hexcolor("#393318"));
                                    ^^^^^^^^
lib/widgets/buttons.dart:46:14: Error: Method not found: 'Hexcolor'.
      color: Hexcolor("#f6f6f9"),
             ^^^^^^^^
lib/widgets/woosignal_ui.dart:197:14: Error: Method not found: 'Hexcolor'.
      color: Hexcolor("#e8e8e8"),
             ^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter_windows_1.22.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'G:\flutter_windows_1.22.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 3s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       311.2s (!)
Exception: Gradle task assembleDebug failed with exit code 1

G:\flutter-woocommerce-app-master\flutter-woocommerce-app-master\LabelStoreMax>flutter run
Launching lib\main.dart on CPH1803 in debug mode...
lib/main.dart:220:23: Error: Method not found: 'Hexcolor'.
        primaryColor: Hexcolor("#2f4ffe"),
                      ^^^^^^^^
lib/main.dart:224:24: Error: Method not found: 'Hexcolor'.
          buttonColor: Hexcolor("#529cda"),
                       ^^^^^^^^
lib/pages/account_billing_details.dart:184:40: Error: The method 'Hexcolor' isn't defined for the class '_AccountBillingDetailsPageState'.
 - '_AccountBillingDetailsPageState' is from 'package:label_storemax/pages/account_billing_details.dart' ('lib/pages/account_billing_details.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                color: Hexcolor("#e8e8e8"),
                                       ^^^^^^^^
lib/pages/account_detail.dart:348:42: Error: The method 'Hexcolor' isn't defined for the class '_AccountDetailPageState'.
 - '_AccountDetailPageState' is from 'package:label_storemax/pages/account_detail.dart' ('lib/pages/account_detail.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                  color: Hexcolor("#fcfcfc"),
                                         ^^^^^^^^
lib/pages/account_order_detail.dart:123:44: Error: The method 'Hexcolor' isn't defined for the class '_AccountOrderDetailPageState'.
 - '_AccountOrderDetailPageState' is from 'package:label_storemax/pages/account_order_detail.dart' ('lib/pages/account_order_detail.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                    color: Hexcolor("#fcfcfc"), width: 1),
                                           ^^^^^^^^
lib/pages/account_shipping_details.dart:203:40: Error: The method 'Hexcolor' isn't defined for the class '_AccountShippingDetailsPageState'.
 - '_AccountShippingDetailsPageState' is from 'package:label_storemax/pages/account_shipping_details.dart' ('lib/pages/account_shipping_details.dart').
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.
                                color: Hexcolor("#e8e8e8"),
                                       ^^^^^^^^
lib/helpers/app_themes.dart:45:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#606060"),
               ^^^^^^^^
lib/helpers/app_themes.dart:49:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#a8a8a8"),
               ^^^^^^^^
lib/helpers/app_themes.dart:54:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#2a5080"),
               ^^^^^^^^
lib/helpers/app_themes.dart:94:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#606060"),
               ^^^^^^^^
lib/helpers/app_themes.dart:98:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#a8a8a8"),
               ^^^^^^^^
lib/helpers/app_themes.dart:103:16: Error: Method not found: 'Hexcolor'.
        color: Hexcolor("#2a5080"),
               ^^^^^^^^
lib/widgets/app_loader.dart:16:37: Error: Method not found: 'Hexcolor'.
  return SpinKitDoubleBounce(color: Hexcolor("#393318"));
                                    ^^^^^^^^
lib/widgets/buttons.dart:46:14: Error: Method not found: 'Hexcolor'.
      color: Hexcolor("#f6f6f9"),
             ^^^^^^^^
lib/widgets/woosignal_ui.dart:197:14: Error: Method not found: 'Hexcolor'.
      color: Hexcolor("#e8e8e8"),
             ^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter_windows_1.22.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'G:\flutter_windows_1.22.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        61.4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by TyagrajBhatt** [comment]
I'm trying to run application using "flutter run" command

**Comment by agordn52** [comment]
Hi, make sure you are on the latest version >= v2.5.0 
https://github.com/woosignal/flutter-woocommerce-app/releases/tag/v2.5.0
Thanks
