### ISSUE TITLE
Facing compilation errors building for Android

### ISSUE THREAD

**Issue by anthonyraj** [woosignal/flutter-woocommerce-app#13]
Hi Project Developer, 

I've just been trying this project today and came into a few issues while compiling an Android build-

1. lib/pages/account_detail.dart:120:7: Error: No named parameter with the name 'resizeToAvoidBottomPadding'.
      resizeToAvoidBottomPadding: false,
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
2. ../../../flutter/flutter_sdk/packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));

There are repeats of errors 1 & 2, which makes me wonder if I should be switching to a particular version of Flutter.

flutter --version
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (11 hours ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
LabelStoreMax (master)*$ flutter channel
Flutter channels:
  master
  dev
  beta
* stable
---

I've been checking out your project and hope to use it/ contribute if it serves our needs.

Regards,
Anthony

**Comment by agordn52** [comment]
Yeah, we've noticed this since the latest Flutter (v2.0.0) release.
We're working on a patch, should be available soon.

**Comment by agordn52** [comment]
@anthonyraj, we've released a new version (v3.0.0) that fixes the errors using Flutter 2.0.0+
Here's a link here - https://github.com/woosignal/flutter-woocommerce-app/releases/tag/v3.0.0

**Comment by anthonyraj** [comment]
Thank you @agordn52 for the quick fix! I'll take a look at the latest version.
