### ISSUE TITLE
add Chinese language

### ISSUE THREAD

**Issue by yangyucacaa** [woosignal/flutter-woocommerce-app#15]
Hello, hope to add Chinese translation, thank you

**Comment by agordn52** [comment]
Yeah, it's something we can add 🙂

**Comment by agordn52** [comment]
[v5.1.0](https://github.com/woosignal/flutter-woocommerce-app/releases/tag/v5.1.0) now supports simplified Chinese and you can update the language through the WooSignal dashboard
