### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by djouamaah** [woosignal/flutter-woocommerce-app#2]
when i run `packages get` i get this issue

> Running "flutter pub get" in LabelStoreMax...                   
> Because every version of flutter_test from sdk depends on path 1.6.2 and dio 3.0.9 depends on path ^1.6.4, flutter_test from sdk is incompatible with dio 3.0.9.
> 
> And because no versions of dio match >3.0.9 <4.0.0, flutter_test from sdk is incompatible with dio ^3.0.9.
> 
> So, because label_storemax depends on both dio ^3.0.9 and flutter_test any from sdk, version solving failed.
> pub get failed (1)
> Process finished with exit code 1

**Comment by agordn52** [comment]
@djouamaah switch to `stable` channel 
```
flutter channel stable
flutter upgrade
flutter doctor -v
```
