### ISSUE TITLE
Cannot fetch products | Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast

### ISSUE THREAD

**Issue by mymakarim** [woosignal/flutter-woocommerce-app#3]
D/ViewRootImpl@3ef15c2[MainActivity]( 4825): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={true 3483224064} changed=false
I/flutter ( 4825): WOOSIGNAL LOG: Parameters: {page: 1, per_page: 50, status: publish, stock_status: instock}
E/flutter ( 4825): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
E/flutter ( 4825): #0      WooSignal.getProducts.<anonymous closure> (package:woosignal/woosignal.dart:151:24)
E/flutter ( 4825): #1      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 4825): #2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 4825): #3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 4825): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 4825): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 4825): #6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 4825): #7      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter ( 4825): #8      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter ( 4825): #9      ApiProvider.post (package:woosignal/networking/api_provider.dart)
E/flutter ( 4825): <asynchronous suspension>
E/flutter ( 4825): #10     WooSignal.getProducts (package:woosignal/woosignal.dart:150:24)
E/flutter ( 4825): #11     _HomePageState._fetchMoreProducts.<anonymous closure> (package:label_storemax/pages/home.dart:74:65)
E/flutter ( 4825): #12     appWooSignal (package:label_storemax/helpers/tools.dart:38:19)
E/flutter ( 4825): <asynchronous suspension>
E/flutter ( 4825): #13     _HomePageState._fetchMoreProducts (package:label_storemax/pages/home.dart:74:39)
E/flutter ( 4825): #14     _HomePageState._home (package:label_storemax/pages/home.dart:53:11)
E/flutter ( 4825): #15     _HomePageState.initState (package:label_storemax/pages/home.dart:47:5)
E/flutter ( 4825): #16     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter ( 4825): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 4825): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 4825): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter ( 4825): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter ( 4825): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter ( 4825): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 4825): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 4825): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #32     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 4825): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
E/flutter ( 4825): #36     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
E/flutter ( 4825): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
E/flutter ( 4825): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
E/flutter ( 4825): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
E/flutter ( 4825): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 4825): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #43     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5830:14)
E/flutter ( 4825): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 4825): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 4825): #46     SingleChildRende

**Comment by woosignal** [comment]
This can be because your store is not linked correctly on WooSignal. Go to the dashboard and reconnect the WooCommerce store to resolve.

Also, always ensure that you are on the latest Flutter build
`flutter channel stable`
`flutter upgrade`
`flutter doctor -v`

Hope that helps.

**Comment by alsayehmoustafa** [comment]
Not Solved
