### ISSUE TITLE
Shipping is not supported for your country

### ISSUE THREAD

**Issue by blackbeario** [woosignal/flutter-woocommerce-app#31]
Hello, this is a beautifully written application, both in the code structure and the accompanying UI and documentation. I have to applaud the amount of work and detail.

Can you please help me understand how to get past this screen. I've tried enabling and disabling shipping in my woosignal.com/dashboard for this store, and neither option seems to provide an answer. When I add a product to the cart and go through the necessary steps to checkout, I am forced to select a shipping option, which returns the error in the issue title "Shipping is not supported for your country". FYI, I've set all the .env variables according to the documentation.

The bool `isShippingSupported` for this check in CheckoutShippingTypePage is instantiated as **true**.

`_getShippingMethods()` ->`wsShipping` returns 1 list item at index [0] with the name "Locations not covered by your other zones"

I know that this check is returning _true_, and that's why I'm getting the message "Shipping is not supported for your country". I just can't figure out why yet.
```
if (_wsShippingOptions.isEmpty) {
    _isShippingSupported = false;
}
```

**customerAddress**, **postalCode**, and **customerCountry** in shipping.locations _all_ have valid values in my debugger at this stage.

I just don't know how to configure this in WooSignal any differently than I've tried with the free options. Is this a paid feature? I mean, I'm sure I can hack the code and insert my own country code, etc. I just want to know what I'm doing wrong.

By the way, I've converted all this to null-safety for this project. Yeah, that was a big task. Thanks for any guidance.

**Comment by blackbeario** [comment]
This eventually resolved on my app after a bit of a wait.

**Comment by agordn52** [comment]
Hi @blackbeario, appreciate your feedback. 

**Re. WooCommerce Shipping**
Yes, you need to add a shipping zone and options in your WordPress dashboard.
Here's a guide [here](https://woocommerce.com/document/setting-up-shipping-zones/)

Hope that helps.
Anthony
