### ISSUE TITLE
Error on Pub get and code

### ISSUE THREAD

**Issue by aslam301** [woosignal/flutter-woocommerce-app#4]
When i run pub get i get this error

and there is more error on dart code

error: The named parameter 'headline4' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:17)
error: The named parameter 'headline3' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:22)
error: The named parameter 'headline2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:26)
error: The named parameter 'headline1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:30)
error: The named parameter 'headline5' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:34)
error: The named parameter 'headline6' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:35)
error: The named parameter 'subtitle1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:39)
error: The named parameter 'bodyText1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:43)
error: The named parameter 'bodyText2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:47)
error: The named parameter 'headline4' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:66)
error: The named parameter 'headline3' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:71)
error: The named parameter 'headline2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:75)
error: The named parameter 'headline1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:79)
error: The named parameter 'headline5' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:83)
error: The named parameter 'headline6' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:84)
error: The named parameter 'subtitle1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:88)
error: The named parameter 'bodyText1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:92)
error: The named parameter 'bodyText2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:96)
error: The named parameter 'headline4' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:115)
error: The named parameter 'headline3' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:119)
error: The named parameter 'headline2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:120)
error: The named parameter 'headline1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:121)
error: The named parameter 'headline5' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:122)
error: The named parameter 'headline6' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:123)
error: The named parameter 'subtitle1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:124)
error: The named parameter 'bodyText1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:125)
error: The named parameter 'bodyText2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:126)
error: The named parameter 'headline4' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:135)
error: The named parameter 'headline3' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:136)
error: The named parameter 'headline2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:137)
error: The named parameter 'headline1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:138)
error: The named parameter 'headline5' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:139)
error: The named parameter 'headline6' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:140)
error: The named parameter 'subtitle1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:144)
error: The named parameter 'bodyText1' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:145)
error: The named parameter 'bodyText2' isn't defined. (undefined_named_parameter at [label_storemax] lib\helpers\app_themes.dart:146)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\about.dart:43)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\about.dart:92)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_billing_details.dart:92)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_detail.dart:90)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_detail.dart:338)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_detail.dart:350)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_detail.dart:373)
error: The getter 'headline4' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_landing.dart:71)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_landing.dart:123)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_order_detail.dart:56)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_order_detail.dart:158)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_order_detail.dart:170)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_register.dart:61)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\account_shipping_details.dart:93)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\browse_category.dart:93)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\browse_category.dart:95)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\browse_search.dart:87)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\browse_search.dart:89)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\cart.dart:179)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\cart.dart:189)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\cart.dart:221)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_confirmation.dart:196)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_confirmation.dart:321)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:386)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:435)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:470)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:505)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:538)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:589)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_details.dart:603)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_payment_type.dart:46)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_payment_type.dart:90)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_shipping_type.dart:204)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_shipping_type.dart:253)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_shipping_type.dart:317)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:63)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:69)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:74)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:81)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:111)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:138)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:147)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\checkout_status.dart:156)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\error_page.dart:49)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\home.dart:151)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\home.dart:156)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\home.dart:167)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\home_menu.dart:42)
error: The getter 'headline3' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\home_search.dart:64)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:116)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:162)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:166)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:194)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:202)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:340)
error: The getter 'headline4' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:359)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:415)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:468)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:483)
error: The getter 'headline4' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\pages\product_detail.dart:509)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\buttons.dart:42)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\buttons.dart:63)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\cart_icon.dart:43)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\menu_item.dart:28)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:31)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:41)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:55)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:77)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:97)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:146)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:154)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:177)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:184)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:240)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:253)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:266)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:272)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:281)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:292)
error: The getter 'headline4' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:339)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:527)
error: The getter 'bodyText1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:533)
error: The getter 'bodyText2' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:545)
error: The getter 'subtitle1' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:551)
error: The getter 'headline6' isn't defined for the class 'TextTheme'. (undefined_getter at [label_storemax] lib\widgets\woosignal_ui.dart:578)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [label_storemax] lib\helpers\tools.dart:72)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [label_storemax] lib\helpers\tools.dart:73)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [label_storemax] lib\helpers\tools.dart:74)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [label_storemax] lib\helpers\tools.dart:75)
info: Unused import: 'package:label_storemax/widgets/woosignal_ui.dart'. (unused_import at [label_storemax] lib\widgets\buttons.dart:13)
info: Unused import: 'package:label_storemax/main.dart'. (unused_import at [label_storemax] test\widget_test.dart:11)

**Comment by agordn52** [comment]
switch to stable channel

``` dart
flutter channel stable
flutter upgrade
flutter doctor -v
```

Closing as its related to #2 (Flutter version being lower than 1.17.0), run the above and it will resolve those errors.
