### ISSUE TITLE
[Feature Request] Add LinkedIn in social links

### ISSUE THREAD

**Issue by jeanmatthieud** [woosignal/flutter-woocommerce-app#43]
Could you please add LinkedIn in the social links menu:
![image](https://user-images.githubusercontent.com/1443167/187194758-d731b55e-84df-4605-bbcd-304c86af8b3e.png)

Asset to include in the project (300x300) in `public\assets\images`: 
![linkedin](https://user-images.githubusercontent.com/1443167/187195434-8a6264ad-b5e9-45b3-bf2f-efc327f4a58f.png)

Source: https://commons.wikimedia.org/wiki/File:LinkedIn_icon_circle.svg

**Comment by agordn52** [comment]
In the next API version for WooSignal, it'll support links better.
The next improvements should be made by the 7th Sept. 

I will ping a notification here once the changes are live.

**Comment by agordn52** [comment]
Hi @jeanmatthieud,

You can now add social links from the WooSignal dashboard.
Make sure your app is [v6.3.0](https://github.com/woosignal/flutter-woocommerce-app/releases/tag/v6.3.0)+

Closing this issue, thanks for the feature request 🚀
