### ISSUE TITLE
[Bug] Shipping zone with postcode limits

### ISSUE THREAD

**Issue by jeanmatthieud** [woosignal/flutter-woocommerce-app#44]
In WooCommerce, you can add a shipping zone defined by a country, and only include some postcodes.

Eg:
![image](https://user-images.githubusercontent.com/1443167/187204418-257e3eb1-8006-4233-a013-5fa1fd8e44d8.png)

The current source code gets a list of locations from WooSignal, which mix country and postcode, without any hierarchy:
![image](https://user-images.githubusercontent.com/1443167/187204806-4a2ff51a-48f1-47a6-b44a-1f596d88ef88.png)

So, the WooSignal server side should be fixed, as well as the mobile app.

*Moreover, the sentence "Shipping is not supported for your country, sorry" should be "Shipping is not supported for your location, sorry"*

**Comment by agordn52** [comment]
Hi @jeanmatthieud,

The `WSShiping` object that's returned from the `getShippingMethods()` response returns:

```json
{
  "parent_id": 1,
  "name": "UK",
  "locations": [
    {
      "code": "GB",
      "type": "country"
    }
  ],
  "methods": {
    "free_shipping": [
      {
        "id": 2,
        "title": "Free shipping",
        "method_id": "free_shipping",
        "cost": "min_amount",
        "minimum_order_amount": "50"
      }
    ],
    "flat_rate": [
      {
        "id": 1,
        "title": "Flat rate",
        "method_id": "flat_rate",
        "cost": "2.99",
        "class_cost": null,
        "calculation_type": null,
        "taxable": false,
        "shipping_classes": [

        ]
      }
    ]
  }
}
```

The app will attempt to match a location from the `country` or `postcode` used in your shipping zone and then gather all the shipping methods that the zone contains. 

Hope that helps. 

Also, I'll get the text changed to "Shipping is not supported for your location, sorry" 👍
