### ISSUE TITLE
[Enhancement] Re-use checkout billing / shipping widgets in customer account

### ISSUE THREAD

**Issue by jeanmatthieud** [woosignal/flutter-woocommerce-app#45]
After editing the billing or shipping address during checkout, you can find the in the "setting" section of the customer account.

Sadly, the widget are not the same (eg: missing phone number in shipping, country selection differs...)

![image](https://user-images.githubusercontent.com/1443167/188595485-75adae2a-d68a-4560-ab21-173d1d2b0947.png)

![image](https://user-images.githubusercontent.com/1443167/188595628-5fa2203f-e7a4-406e-9fcc-b4fbb86b5d31.png)

**Comment by agordn52** [comment]
Hi @jeanmatthieud,

This is a great idea! I've implemented it in [v6.3.0](https://github.com/woosignal/flutter-woocommerce-app/releases/tag/v6.3.0).

Closing this issue, thanks for feature request.
