### ISSUE TITLE
Refactor app into small widgets

### ISSUE THREAD

**Issue by EmadBustati** [woosignal/flutter-woocommerce-app#5]
Is it possible to convert this app into Flutter WooCommerce Widgets library it would be more useful and could minimize the efforts when building multiple stores. 

After the refactoring it would be possible to build assembled app from the core widgets library, this would give us more fixable themes and solve sync issue when any new changes or features add to the core widgets.

**Comment by agordn52** [comment]
In future please forward any enhancements or features to support@woosignal.com this is not an issue with the template.

The short answer to that idea is maybe in the future. Yes, it would be more ideal to allow this, however, at this point in time, we're focused on keeping our plugins updated.

Closing #5 as it's not an issue.
