### ISSUE TITLE
Unable to apply coupon.

### ISSUE THREAD

**Issue by Gursewak-Uppal** [woosignal/flutter-woocommerce-app#52]
Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'String?'

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/28809960/210302105-32b8d95a-c910-4079-99fc-a044213f8c91.png">

**Comment by agordn52** [comment]
Hi,

Could you contact [support](https://woosignal.com/support) about the issue?

Thanks,
Anthony
