### ISSUE TITLE
plz add your google.json

### ISSUE THREAD

**Issue by mynameismhmd** [woosignal/flutter-woocommerce-app#55]

**Comment by agordn52** [comment]
@mynameismhmd,

You need to add your own to the project

**Comment by mynameismhmd** [comment]
my own doesn't work

**Comment by mynameismhmd** [comment]
plz add it why is it not there

**Comment by mynameismhmd** [comment]
plus I dont have my own project

**Comment by jeanmatthieud** [comment]
> plz add it why is it not there

Each firebase project must have it own "google-services.json" file.
Please read the official documentation : https://support.google.com/firebase/answer/7015592?hl=en

**Comment by mynameismhmd** [comment]
I dont have my own project plz add it

**Comment by mynameismhmd** [comment]
I use the peoples google.json all the time

**Comment by jeanmatthieud** [comment]
> I use the peoples google.json all the time

It's a mistake... you must create your own project.

**Comment by mynameismhmd** [comment]
no it is not I hope you add it in the future it looks horrible without it my friend who sent me it also said that
