### ISSUE TITLE
Is it safe to embed api key in .env file

### ISSUE THREAD

**Issue by cwengc** [woosignal/flutter-woocommerce-app#58]
APP_KEY="your app key"
# App key from WooSignal link: https://woosignal.com/dashboard

# *<! ------ STRIPE (OPTIONAL) ------!>*

STRIPE_ACCOUNT=null
# Stripe account key from WooSignal https://woosignal.com/dashboard

**Comment by agordn52** [comment]
Hi @cwengc,

It's safe until it's shared publicly.
I wouldn't recommend committing your .env file to a public repository because it'll contain the app key.

Hope that helps.
