### ISSUE TITLE
No results on Shipping Methods

### ISSUE THREAD

**Issue by ezioauditore0101** [woosignal/flutter-woocommerce-app#9]
E/flutter ( 8067): <asynchronous suspension>

**Comment by agordn52** [comment]
You need shipping methods enabled via your WooCommerce store.

Follow the official guide here to add shipping zones and methods https://docs.woocommerce.com/document/setting-up-shipping-zones/

The app will pull shipping methods from the zones assigned.

closing #9

**Comment by ezioauditore0101** [comment]
there are 2 zones added already, yet it doesn't show me any shipping options.
